"""Typeset equivalents of ledger statements; domains and limits remain verbatim."""
STATEMENTS={
'L02':r'The panel pullback metric is \(I_2\). The decoder \(D_i(q+ip)=qt_i+pe_z\) is isometric; \(ED=I\), while \(DE\) is the ambient tangent projector.',
'L03':r'\(T_{ij}=t_it_j^T+e_ze_z^T\) satisfies \(T_{ij}T_{jk}=T_{ik}\). Closed products restrict to identity on \(W_i\).',
'L04':r'The pre-stage increment is \(-\nabla\mathcal V\), with \(\mathcal V=\eps\sum_i(s_i^2/4-k_is_i/2)+(g/2)\sum_{\{i,j\}}|z_i-z_j|^2\), \(s_i=|z_i|^2\). The complete intensity increment includes the squared norm of the pre-increment.',
'L05':r'For \(\eps\ne0\), fixed states on the nonzero common-channel line form \(\sqrt{k}e^{i\chi}\one\) exactly when \(k>0\).',
'L06':r'The amplitude block is \((1-2\eps k)I+g\Delta\); the phase block is \((I+3\lambda\Delta)(I+g\Delta)\).',
'L07':r'\(\mu_a=1-2\eps k-gh_m\), \(\mu_\phi=(1-gh_m)(1-3\lambda h_m)\), and \(h_m=4\sin^2(\pi m/N)\).',
'L08':r'Strict normal contraction is equivalent to \(|\mu_a(m)|<1\) for every m and \(|\mu_\phi(m)|<1\) for nonzero m; it yields local finite-N attraction modulo common phase.',
'L09':r'For fixed m and \(D_\phi=g+3\lambda>0\), \(\mu_\phi(2\pi m/N)^{\lfloor\tau N^2\rfloor}\) tends uniformly on bounded nonnegative tau intervals to \(e^{-4\pi^2D_\phi m^2\tau}\), with \(O(N^{-2})\) error.',
'L10':r'The local analytic positive solution of \(\eps r_i(k_i-r_i^2)+g(\Delta r)_i=0\) has \((2\eps kI-g\Delta)u=\eps\sqrt{k}\,\kappa\). For three-periodic zero-mean kappa, \(u=\eps\sqrt{k}\,\kappa/(2\eps k+3g)\).',
'L11':r'\(P=R^{-1}H_rR\), \(H_rr=r\), and \(R^2P=P^TR^2\). The inner product has weights \(r_i^2\) and Dirichlet form \(g\sum_{\{i,j\}}r_ir_j(f_i-f_j)^2\).',
'L12':r'\(J_\phi=S_\phi P\), with \(S_\phi=I+\ell\Delta\), \(\ell=3\lambda\); the amplitude block is \(H_r-2\eps R^2\). There is no first-order amplitude/phase mixing.',
'L13':r'\(\mathcal C_{\rm cyc}=g\ell(1-3\ell)(a-b)(a-c)(b-c)\mathcal K/(a^2b^2c^2)\), where \(\mathcal K=g^2\ell\sigma_1^3+[g^2(1-2\ell)-g\ell]\sigma_1\sigma_2+(3g\ell-g+\ell)\sigma_3\).',
'L14':r'With positive off-diagonals, \(\mathcal C_{\rm cyc}=0\) iff positive diagonal balance exists. One choice is \(W=\diag(J_{21}J_{31},J_{12}J_{31},J_{13}J_{21})\). Exceptional factors are \(g=0\), \(\ell=0\), \(\ell=1/3\), equal radius pairs, or \(\mathcal K=0\).',
'L15':r'\(\mathcal C_{\rm cyc}=g\ell(1-3\ell)K_0[\eps/(2\eps k+3g)]^3V(\kappa)\eta^3+O(\eta^4)\), with \(K_0=g(9g-1)+\ell(1-3g)^2\).',
'L16':r'For \(N\ge6\) and \(g\ell\ne0\), distinct positive repeated radii forbid positive diagonal balance. For \((a,a,c)\), it exists iff \(\ell-g-g\ell(2a/c+c/a)=0\), and then \(W=R\).',
'L17':r'A real J admits SPD G with \(GJ=J^TG\) iff its spectrum is real and semisimple. All solutions are \(G=V^{-T}KV^{-1}\), with K SPD and commuting with the real eigenvalue matrix. Positive sums of \(E_\rho^TE_\rho\) also construct solutions.',
'L18':r'\(M_3=\sigma R^{-1}-\one\one^T\) is symmetric positive semidefinite with kernel r; its positive roots have sum h and product t. The quotient polynomial is \(Q(\xi)=\xi^2-d(2-gh)\xi+d^2(1-gh+g^2t)\), with \(\mathcal D_3=d^2g^2(h^2-4t)\ge0\).',
'L19':r'For \(M_3w_\alpha=\mu_\alpha w_\alpha\), \(w_\alpha\perp r\), set \(v_\alpha=R^{-1}w_\alpha\), \(p_\alpha=1-g\mu_\alpha\). A full defect occurs at \(dp_\alpha=1\) with \(\ell p_\alpha\one^Tv_\alpha\ne0\).',
'L20':r'\(\mathcal D_3=6d^2g^2[\eps/(2\eps k+3g)]^2\sum_i\kappa_i^2\eta^2+O(\eta^3)\). No order produces complex transverse roots on a positive triad.',
'L21':r'For \(\phi_{n,\alpha}=z^nv_\alpha\), \(z^q=1\), the exact block is \(J(z)=(I+\ell D(z))R^{-1}H_r(z)R\), where the corner entries of the cycle block \(D(z)\) are \(z^{-1},z\), its other off-diagonals are one and its diagonal is minus two.',
'L22':r'\(\det(\xi I-J(z))=\xi^3-T_B\xi^2+B_B(z)\xi-D_B(z)\), with coefficients in \eqref{eq:BT}--\eqref{eq:BD}. In particular \(\Gamma_B=\ell g[\ell(1+3g)-g](a-b)(a-c)(b-c)/(abc)\) and \(\im B_B=-\Gamma_B\sin\theta\).',
'L23':r'Nonzero \(\Gamma_B\sin\theta\) forces non-real roots. For real cubic coefficients, positive discriminant gives three simple real roots, negative gives a complex pair, and zero requires a rank/minimal-polynomial test.',
'L24':r'For \(q\ge3\), three distinct radii and \(g\ell[\ell(1+3g)-g]\ne0\) force non-real spectrum. \(\Gamma_B\) is cubic in weak inequality; simple nonzero roots have the cubic imaginary shift in Section~\ref{sec:bloch}.',
'L25':r'At \(z=-1\), \(\mathfrak D_\pi=6g^2(1-\ell)^2\sum_i v_i^2(3E_\pi)^4\eta^2+O(\eta^3)\), where \(E_\pi=g+\ell-5g\ell\).',
'L26':r'For \(r=(1-\tau,1,1+\tau)\), \(g=(1-\tau^2)/4\), \(\ell=1\), the exact block is \(J(-1)=(\tau^2/4)(1,-1,1)^T(1+\tau,2,1-\tau)\). It has rank one, square zero, and Jordan sizes \(2+1\).',
'L27':r'With the same \(r,g,k_i,\eps\) and \(\ell=1+\delta\), the coefficients are \eqref{eq:unfoldcoeff}, and \(\mathfrak D_\pi=(27/2)\tau^{12}\delta^3+O(\delta^4)\).',
'L28':r'The generators act by \(C_3:(q,p)\mapsto(Pq,Pp)\), \(\sigma_v:(q,p)\mapsto(-Q_vq,Q_vp)\), and \(\sigma_h:(q,p)\mapsto(q,-p)\).',
'L29':r'Real-linear polar and axial map dimensions are 2 and 2; homogeneous quadratic dimensions are 5 and 3. Complete bases appear in Theorem~\ref{thm:observables}.',
'L30':r'The optional common-phase-invariant quadratic polar space is spanned by \(N_f(au+bv)\), \(N_f(u^2+v^2)\), \(\Gamma_{\rm ch}e_z\). The axial invariant space is spanned by W.',
'L31':r'\(C_{\rm ch}=q\times p=e\times(av-bu)+u\times v\). Its horizontal-axial projection is \(W=T_fC_{\rm ch}=\sqrt3(bN_fu-aN_fv)\); its vertical-polar projection is \((e^TC_{\rm ch})e_z=\Gamma_{\rm ch}e_z\).',
'L32':r'For transverse u,v, \(\|N_f(u^2)\|^2=\|u\|^4/4\), \(\|N_f(uv)\|^2=\|u\|^2\|v\|^2/4\), and \(\Gamma_{\rm ch}^2=3(\|u\|^2\|v\|^2-(u\cdot v)^2)\). Products inside \(N_f\) are entrywise.',
'L33':r'\(\Delta V=V(F(\Omega))-V(\Omega)\). Polynomial increments follow substitution; local response at a fixed background is \(DV(\Omega_*)DF(\Omega_*)\).',
'L34':r'\(D:\C^3\to\bigoplus_i W_i\) has inverse E. The full section evolves by \(DFE\), with transported graph increment and outward-normal phase rotation.',
'L35':r'For constant face extensions, ambient equality at every seam requires \(q=0,p=be\); matched parallelism requires \(q=ae,p=be\).',
'L36':r'Degree (0,1,2) counts are face scalar/normal (1,1,8), tangent (0,4,8), ambient-face (1,5,16), vertical seam (0,2,4), rim scalar (1,1,5), and rim vector (1,3,12).',
'L37':r'Lens and incident data pass through \(\C^2\otimes\C^3\), fixed \(U^n\), extraction \(\chi^\dagger\otimes I\), \(\Omega_0\), then \(D\Omega_0\). Preparation internals have no material shell attachment and no feedback enters F.',
'L38':r"\(\mathcal AF=F_{\mathcal A}\mathcal A\) on the image exists iff \(\mathcal A(x)=\mathcal A(x')\) implies \(\mathcal A(Fx)=\mathcal A(Fx')\).",
'L39':r'Single-face values, intensities, raw chirality, W, Gamma and joint (W,Gamma) generally fail closure. At \(g=0\), \(I_i^+=I_i[1+\eps(k_i-I_i)]^2\).',
'L40':r'\(\mathcal H=\Omega\Omega^\dagger\) closes when all diagonal entries of \(M\mathcal HM^T\) are positive: \(\mathcal H^+=U_\delta M\mathcal HM^TU_\delta^\dagger\), with delta from imaginary cubes of normalized transposed coherence entries.',
'L41':r'\(S_G=qq^T+pp^T\) also closes on the regular pre-stage domain: equal Gram factors differ by \(O(2)\), namely common phase and/or conjugation.',
'L42':r'For \(\eps=g=0,\lambda=1/10\), inputs \((1,-1,0)\) and \(e^{i\pi/6}(1,-1,0)\) have identical coherences and real Grams. Outputs have \(\mathcal H_{12}^+=-1\) versus \(-e^{-i/5}\), and \(S_{G,12}^+=-1\) versus \(-\cos(1/5)\).',
}
