"""Unprotected installed-byte inventories. These do not identify loaded instructions."""
import hashlib
import ctypes
import importlib.metadata
import json
from pathlib import Path
import platform
import struct
import sys

DISTRIBUTIONS = ("numpy", "trioctagon-analysis", "trioctagon-historical-protocol", "trioctagon-historical-kernel")


def sha(raw):
    return hashlib.sha256(raw).hexdigest()


def inventory(name):
    if name not in DISTRIBUTIONS:
        raise ValueError("distribution is outside the fixed Historical closure")
    root = Path(sys.prefix).resolve()
    dist = importlib.metadata.distribution(name)
    rows = []
    for item in dist.files or ():
        path = Path(dist.locate_file(item)).resolve()
        if not path.is_relative_to(root) or not path.is_file():
            raise ValueError("installed inventory member escapes isolated prefix or is missing")
        raw = path.read_bytes()
        rows.append(dict(path=path.relative_to(root).as_posix(), bytes=len(raw), sha256=sha(raw)))
    if not rows:
        raise ValueError("missing installed distribution inventory")
    rows.sort(key=lambda row: row["path"])
    if len({row["path"].casefold() for row in rows}) != len(rows):
        raise ValueError("duplicate installed members")
    return dict(id=name, version=dist.version, members=rows)


def manifest_sha(value):
    # This is a byte identity for an external installed-inventory JSON document,
    # not a new canonical protocol codec or scientific digest scope.
    return sha(json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode("utf-8"))


def runtime():
    # platform.platform() queries the processor through a helper subprocess on
    # Windows. Runtime identity must not depend on that unrelated process or
    # change when the fixed two-process resource job correctly refuses it.
    windows = sys.getwindowsversion() if sys.platform == "win32" else None
    operating_system = "win32-"+".".join(str(x) for x in windows[:3]) if windows else sys.platform
    return dict(implementation=platform.python_implementation(), version=platform.python_version(),
                platform=operating_system, architecture=str(struct.calcsize("P")*8)+"bit")


def verify_numeric_environment():
    """Read, never repair, this worker thread's Windows binary64 control state."""
    if sys.platform!='win32' or struct.calcsize('P')!=8:
        raise ValueError('local numeric certification requires Windows 64bit')
    control=ctypes.CDLL('ucrtbase')._controlfp_s
    control.argtypes=(ctypes.POINTER(ctypes.c_uint),ctypes.c_uint,ctypes.c_uint)
    control.restype=ctypes.c_int
    value=ctypes.c_uint()
    if control(ctypes.byref(value),0,0) or value.value & (0x00000300|0x03000000):
        raise ValueError('nearest-even and gradual subnormal modes are required')
    import numpy as np
    tiny=np.float64(float.fromhex('0x1p-1022'))
    with np.errstate(under='ignore'):
        if float(tiny/np.float64(2.)).hex()!='0x0.8000000000000p-1022':
            raise ValueError('NumPy gradual-underflow probe failed')


def verify_runtime_closure():
    """Observe live imports; this is not loaded-instruction attestation."""
    forbidden={'kernel_physics','kernel_TO','torment_service','trioctagon_ui','sympy'}
    generic={'trioctagon_analysis','trioctagon_analysis.codec','trioctagon_analysis.digests',
             'trioctagon_analysis.errors','trioctagon_analysis.schema','trioctagon_analysis.envelope'}
    root=Path(sys.prefix).resolve()
    for name,module in tuple(sys.modules.items()):
        if name.split('.')[0] in forbidden:
            raise ValueError('forbidden scientific runtime import: '+name)
        if name.startswith('trioctagon_analysis') and name not in generic:
            raise ValueError('non-generic Core dependency: '+name)
        if name.startswith(('trioctagon_historical','trioctagon_analysis','numpy')):
            origin=getattr(module,'__file__',None)
            if origin and not Path(origin).resolve().is_relative_to(root):
                raise ValueError('runtime module is outside the admitted installed prefix')


def verify_inventory(expected):
    actual = inventory(expected["id"])
    if actual != expected:
        raise ValueError("installed content differs: " + expected["id"])
    # Catch unlisted files in the implementation package, including accidental
    # checkout substitution, injected modules and generated bytecode.
    if expected["id"] == "trioctagon-historical-kernel":
        package = Path(__file__).resolve().parent
        root = Path(sys.prefix).resolve()
        listed = {row["path"] for row in actual["members"] if row["path"].startswith(package.relative_to(root).as_posix()+"/")}
        present = {p.relative_to(root).as_posix() for p in package.rglob("*") if p.is_file()}
        if listed != present:
            raise ValueError("implementation package contains unlisted or missing files")
    return actual
